language: node_js
nodejs:
- 10.12.0
addons:
  sshknownhosts:
  - 142.93.48.135
env:
  global:
  - REMOTEAPPDIR=/var/www/exodus.calebissharp.com/
  - REMOTEUSER=deploy
  - REMOTEHOST=142.93.48.135
  - PORT=80
install:
- yarn
script:
- yarn test
deploy:
  provider: script
  script: ssh deploy@DROPLET_IP 'cd exodus/; git checkout master; git pull; yarn;
    yarn restart;'
  on:
    branche: master
before_install:
- openssl aes-256-cbc -K $encrypted_f6534a27c58f_key -iv $encrypted_f6534a27c58f_iv
  -in deploy_rsa.enc -out deploy_rsa -d
