language: node_js
nodejs:
- 10.12.0
addons:
  sshknownhosts:
  - 142.93.48.135
env:
  global:
  - REMOTEAPPDIR=/var/www/MYDOMAIN.COM/
  - REMOTEUSER=deploy
  - REMOTEHOST=142.93.48.135
  - PORT=8080
install:
- yarn
beforescript:
- chmod 600 deploy && mv deploy ~/.ssh/idrsa
script:
- yarn test
after_success:
- "./scripts/deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_f6534a27c58f_key -iv $encrypted_f6534a27c58f_iv
  -in deploy.enc -out deploy -d
