language: node_js
nodejs:
  - 10.12.0
addons:
  ssh_known_hosts: exodus.calebissharp.com
env:
  global:
    - REMOTEAPPDIR=/var/www/exodus.calebissharp.com/
    - REMOTEUSER=deploy
    - REMOTEHOST=142.93.48.135
    - PORT=80
install:
  - yarn
script:
  - yarn test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_f6534a27c58f_key -iv $encrypted_f6534a27c58f_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script:
    ssh deploy@exodus.calebissharp.com 'cd exodus/; git checkout master; git pull -f; yarn;
    yarn restart;'
  on:
    branche: master
